### PR TITLE
IR projector

### PR DESCRIPTION
**Pull request by zhumxcq**
Able to change IR projector intensity, wait I don't know what I'm doing -__- I just want to make a new function to change IR projector intensity...

### CODE REVIEW

**Comment by piedar** [comment]
I don't know what IR intensity means and there's no reference in the [protocol documentation](http://openkinect.org/wiki/Protocol_Documentation).  I'm closing this pull request because it doesn't make sense to merge `debian` into `master`.

**Comment by zhumxcq** [comment]
Hey its cmd 0x0015, I'm not sure how to do a pull request properly, but 
basically I want to add a function like
freenect_set_ir_brightness(uint8_t brightness) to the library header.

**Comment by piedar** [comment]
OK, I see it now.  I created #433.

**Comment by zhumxcq** [comment]
Hey,

Are you the package maintainer? If so, find attached the .patch file 
that adds the feature. There may be need to do some error checking or 
function printing though.

Regards,
Meng Xi Zhu

**Comment by piedar** [comment]
Github [doesn't support email attachments](https://github.com/blog/811-reply-to-comments-from-email), so I think it ate your patch.  If you'd be so kind to paste it in a comment over at #433, I can schedule it for merge.  Thank you.

**Pull request closed without merging**
