### PR TITLE
bugfix for open subdevices opening wrong device / not opening all devices

### PR DESCRIPTION
**Pull request by ofTheo**
I have been dealing with this issue for a while now. 
It mainly comes up when using multiple Kinects, especially if they are of a different type ( i.e: a mixture of 1473, K4W and 1414 models ).  

This PR rewrites the motor and audio opening code in fnusb_open_subdevices so that it now only matches audio and motor devices that have the same libusb parent as the camera.  The old code was doing a for loop through all devices in the system and trying to match based on the order listed.  My guess is that this approach fails to get the correct audio device and therefore doesn't upload the audio firmware to the correct kinect. 

In test, this produces much more stable results and makes it so I can open three different devices ( a 1473, K4w and 1414 ) at the same time with no error and every time.  ( the current master works sometimes, when the audio firmware has been uploaded, but on first connection to the computer fails and needs several open / close to get devices working ). 

In addition the code in the current master produces the following message when trying to open three devices:

`Failed to open motor subddevice or it is not disabled. Failed to open audio subdevice `

And not all devices load ( see image ) 

screen shot 2016-08-24 at 3 21 45 pm

The code in this PR doesn't get this error and loads and runs all kinects correctly.  ( see image ) 

screen shot 2016-08-24 at 2 26 47 pm

### CODE REVIEW

**Comment by piedar** [comment]
Wow!  Can't wait to try it.

**Comment by ofTheo** [comment]
@piedar - yeah would be good to test with different setups.  I tested it quite heavily on OS X and nothing in the changes should be platform specific, but would be good to try it out on other setups.

**Comment by piedar** [comment]
Works for me on Linux - nice simplification!

Please sign your commit with `git commit --amend -s`; if I sign it myself, Github shows "Closed" instead of "Merged".

**Comment by ofTheo** [comment]
thanks @piedar good to hear! 
apologies about forgetting the sign off :)

**Comment by piedar** [comment]
Something went weird and it ended up with 3 commits, so I just cherry-picked b483354.  Thanks!

**Pull request closed without merging**
